### ISSUE TITLE
Option to send POST requests instead of GET

### ISSUE THREAD

**Issue by eipiminus1** [moritzmair/touchbell#9]
Instead of triggering a GET endpoint I would like to trigger a POST endpoint like [this](https://www.cloudamqp.com/docs/http.html#publish-with-http) one:
```bash
curl -XPOST -d'{"properties":{},"routing_key":"my_key","payload":"my body","payload_encoding":"string"}' https://username:password@hostname/api/exchanges/vhost/amq.default/publish

Response: {"routed":true}
```
This means in the admin interface I need to be able to
a) Choose between different HTTP verbs
b) provide a string that should be sent as payload in the request

Why?
---
Instead of having to host my own server or patching multiple cloud services together the added flexibility would simplify our bell setup significantly.

@cklos and I would be willing to get our hands dirty by copy and pasting some code but we haven't touch ruby before :D

**Comment by moritzmair** [comment]
I will consider this in a future update. Thanks for the request :-)

**Comment by Larsg7** [comment]
We are currently working on such a feature (we are using Mattermost internally). Will publish a pull request soon.

**Comment by moritzmair** [comment]
merged the pull request. Thanks for your work @inheaden ( @chaithanya008  and @Larsg7 )
